### ISSUE TITLE
userconf files not working

### ISSUE THREAD

**Issue by stephenl03** [boranblok/nntpPoster#20] opened 2017-03-08 22:22 UTC
OS: CentOS 7
Version: 0.9.2
Install location: /opt/nntpPoster

I copied /opt/nntpPoster/Util/userconf/readme.txt to /opt/nntpPoster/Util/userconf/10-MyConfiguration.ini made my adjustments and in the logs was receiving: 
```2017-03-08 06:49:30,375 DEBUG 160 nntpPoster.PostingThread - Constructing new client.
2017-03-08 06:49:30,496 DEBUG 154 PostingNntpClient.SimpleNntpPostingClient - Connecting to newshost.
2017-03-08 06:49:30,710 DEBUG 156 nntpPoster.PostingThread - Disposing client because of exception.
2017-03-08 06:49:30,711 WARN 156 nntpPoster.PostingThread - Posting yEnc message failed
System.Net.Sockets.SocketException (0x80004005): Could not resolve host 'Address of news host'
  at System.Net.Dns.Error_11001 (System.String hostName) [0x00015] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Net.Dns.GetHostByName (System.String hostName) [0x00024] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Net.Dns.GetHostEntry (System.String hostNameOrAddress) [0x00061] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Net.Dns.GetHostAddresses (System.String hostNameOrAddress) [0x00065] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Net.Sockets.TcpClient.Connect (System.String hostname, System.Int32 port) [0x00000] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Net.Sockets.TcpClient..ctor (System.String hostname, System.Int32 port) [0x00006] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at PostingNntpClient.SimpleNntpPostingClient.Connect () [0x00028] in <8edf3e76744b430dacce359e7728ce11>:0
  at nntpPoster.PostingThread.PostMessage (nntpPoster.nntpMessage message) [0x0003b] in <7c82b70e575f4f02810136416a107010>:0
```
I then tried to rename the file to  /opt/nntpPoster/Util/userconf/default.ini with no success. The only way I got around the error was to edit /opt/nntpPoster/conf/default.ini

I am now running into the same issue with /opt/nntpPoster/Util/userconf/watchfolders/default.ini The changes I have made in there are not being applied. I am restarting the daemon after every file change to ensure they are being read on startup. I do not see any errors related to not being able to read the config either. 

Stephen

**Comment by boranblok** [comment] 2017-08-08 14:13
hmmh,, sorry that I come to you so late with a reply. IRL has been (and still is) a bit hectic.

I would think the application possible is running in a wrong path and might be looking for ini files in the wrong location.

Do you still have this issue? If so I can see to add some more logging to the initialisation part to see what is really happening there.

**Comment by boranblok** [comment] 2017-09-21 11:20
Closing due to no reply/confirmation that the issue is still present.

**Closed by boranblok** 2017-09-21 11:20 UTC
